version: '2'
services:
  mariadb:
    build: ${MARIADB_DIR}
    image: ${IMG_MARIADB_NAME}
    container_name: ${CON_MARIADB_NAME}
    restart: always
    env_file: .env 
    networks: 
      - net-wordpress
    ports: 
      - '3306'
    volumes:
      - vol-mariadb:${MARIADB_DATA_DIR}
  wordpress:
    depends_on:
      - mariadb
    build: ${WORDPRESS_DIR}
    image: ${IMG_WORDPRESS_NAME}
    container_name: ${CON_WORDPRESS_NAME}
    restart: always
    env_file: .env 
    ports: 
      - '9000'
    networks: 
      - net-wordpress
    volumes:
      - vol-wordpress:${WORDPRESS_DATA_DIR}
    #command: mysql -u root -h mariadb -p${MARIADB_PWD}
  nginx:
    depends_on:
      - wordpress
      - mariadb
    build: ${NGINX_DIR}
    image: ${IMG_NGINX_NAME}
    container_name: ${CON_NGINX_NAME}
    restart: always
    ports: 
      - '443:443'
    networks: 
      - net-wordpress
    volumes:
      - vol-wordpress:${NGINX_DATA_DIR}
networks: 
  net-wordpress:
    driver: bridge
    name: net-wordpress

volumes:
  vol-mariadb:
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/mariadb
      o: bind
      type: none
    name: vol-mariadb
  vol-wordpress:
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/wordpress
      o: bind
      type: none
    name: vol-wordpress
