version: '2'
services:
  mariadb:
    build: ${MARIADB_DIR}
    image: mariadb
    container_name: mariadb
    env_file: .env 
    networks: 
      - net-wordpress
    volumes:
      - volume_db:${MARIADB_DATA_DIR}
  wordpress:
    depends_on:
      - mariadb
    build: ${WORDPRESS_DIR}
    image: wordpress
    container_name: wordpress
    env_file: .env 
    ports: 
      - '9000'
    networks: 
      - net-wordpress
    volumes:
      - volume_wp:${WORDPRESS_DATA_DIR}
  nginx:
    depends_on:
      - wordpress
      - mariadb
    build: ${ENGINX_DIR}
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - '443:443'
    networks: 
      - net-wordpress
    volumes:
      - volume_wp:${NGINX_DATA_DIR}
networks: 
  net-wordpress:
    driver: bridge
    name: net-wordpress

volumes:
  volume_db:
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/mariadb
      o: bind
      type: none
    name: volume_db
  volume_wp:
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/wordpress
      o: bind
      type: none
    name: volume_wp