version: '2'
services:
  mariadb:
    build: ${MARIADB_DIR}
    image: mariadb42
    container_name: mariadb42
    env_file: .env 
    networks: 
      - net-wordpress
    volumes:
      - volume_db:${MARIADB_DATA_DIR}
  wordpress:
    depends_on:
      - mariadb
    build: ${WORDPRESS_DIR}
    image: wordpress42
    container_name: wordpress42
    env_file: .env 
    ports: 
      - '3306'
    networks: 
      - net-wordpress
  nginx:
    depends_on:
      - wordpress
      - mariadb
    build: ${ENGINX_DIR}
    image: nginx42
    container_name: nginx42
    restart: always
    ports: 
      - '443:443'
    networks: 
      - net-wordpress
networks: 
  net-wordpress:
    driver: bridge
    name: net-wordpress

volumes:
  # Volume for MariaDB
  volume_db:
    # Driver Selection among Local, Volume (Docker Volume), Temporary File System (tmpfs)
    driver: local
    # Driver Options for the Selection
    driver_opts:
      # Binding Path
      device: ${VOLUMES_DIR}/mariadb
      # Mount Option (Reference from mount Command Manual)
      o: bind
      # Volume Type
      type: none
    # Volume Name (Not to Make srcs Prefix)
    name: volume_db